server:
  port: 8081

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/shopease_user_db}
      database: shopease_user_db

app:
  jwt:
    secret: ${JWT_SECRET:}
    expiration: 86400000
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
